apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin
        imagePullPolicy: Always
        ports:
        - containerPort: 9411
        readinessProbe:
          httpGet:
            path: /
            port: 9411
          initialDelaySeconds: 5
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "15"]
