apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-approval-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight-approval-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: flight-approval-service
    spec:
      containers:
      - name: flight-approval-service
        image: alphastream99/approval-service:approvalservice
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
        readinessProbe:
          httpGet:
            path: /
            port: 8090
          initialDelaySeconds: 5
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "15"]
