apiVersion: v1
kind: Service
metadata:
  name: flight-approval-service
  labels:
    app: flight-approval-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8090
  selector:
    app: flight-approval-service
  type: ClusterIP