apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reporting-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: reporting-service
    spec:
      containers:
      - name: reporting-service
        image: alphastream99/reporting-service:reportingservice
        imagePullPolicy: Always
        ports:
        - containerPort: 8097
        readinessProbe:
          httpGet:
            path: /
            port: 8097
          initialDelaySeconds: 30
          failureThreshold: 120
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "15"]
