apiVersion: v1
kind: Service
metadata:
  name: reporting-service
  labels:
    app: reporting-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8097
  selector:
    app: reporting-service
  type: ClusterIP