kafka:
  producer:
    flight-request:
      properties:
        transactional.id: flight-request-producer
        bootstrap.servers: localhost:9092
        schema.registry.url: http://localhost:8081
        acks: all
        retries: 3
        batch.size: 16384
        linger.ms: 1
        buffer.memory: 33554432
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
  channel-mapping:
    flightRequest: flight-request-topic
server:
  port : 8099