apiVersion: apps/v1
kind: Deployment
metadata:
  name: airplane-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airplane-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: airplane-service
    spec:
      containers:
      - name: airplane-service
        image: <idk-what-comes-here-but-mostly-the-directory>:airplane-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8099
        readinessProbe:
          httpGet:
            path: /
            port: 8099
          initialDelaySeconds: 5
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "15"]
