apiVersion: v1
kind: Service
metadata:
  name: airplane-service
  labels:
    app: airplane-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8099
  selector:
    app: airplane-service
  type: ClusterIP