/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro.schemas.v1;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class FlightRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4679936722238857466L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FlightRequest\",\"namespace\":\"avro.schemas.v1\",\"fields\":[{\"name\":\"flightCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"fromCoordinates\",\"type\":[{\"type\":\"record\",\"name\":\"Coordinates\",\"fields\":[{\"name\":\"lat\",\"type\":\"float\"},{\"name\":\"lon\",\"type\":\"float\"}]},\"null\"]},{\"name\":\"toCoordinates\",\"type\":[\"Coordinates\",\"null\"]},{\"name\":\"uuid\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"traceId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"parentId\",\"type\":\"long\"},{\"name\":\"startTimestamp\",\"type\":\"long\"},{\"name\":\"serviceName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FlightRequest> ENCODER =
      new BinaryMessageEncoder<FlightRequest>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FlightRequest> DECODER =
      new BinaryMessageDecoder<FlightRequest>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<FlightRequest> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<FlightRequest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<FlightRequest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FlightRequest>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this FlightRequest to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a FlightRequest from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a FlightRequest instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static FlightRequest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String flightCode;
   private avro.schemas.v1.Coordinates fromCoordinates;
   private avro.schemas.v1.Coordinates toCoordinates;
   private java.lang.String uuid;
   private java.lang.String traceId;
   private long parentId;
   private long startTimestamp;
   private java.lang.String serviceName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FlightRequest() {}

  /**
   * All-args constructor.
   * @param flightCode The new value for flightCode
   * @param fromCoordinates The new value for fromCoordinates
   * @param toCoordinates The new value for toCoordinates
   * @param uuid The new value for uuid
   * @param traceId The new value for traceId
   * @param parentId The new value for parentId
   * @param startTimestamp The new value for startTimestamp
   * @param serviceName The new value for serviceName
   */
  public FlightRequest(java.lang.String flightCode, avro.schemas.v1.Coordinates fromCoordinates, avro.schemas.v1.Coordinates toCoordinates, java.lang.String uuid, java.lang.String traceId, java.lang.Long parentId, java.lang.Long startTimestamp, java.lang.String serviceName) {
    this.flightCode = flightCode;
    this.fromCoordinates = fromCoordinates;
    this.toCoordinates = toCoordinates;
    this.uuid = uuid;
    this.traceId = traceId;
    this.parentId = parentId;
    this.startTimestamp = startTimestamp;
    this.serviceName = serviceName;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return flightCode;
    case 1: return fromCoordinates;
    case 2: return toCoordinates;
    case 3: return uuid;
    case 4: return traceId;
    case 5: return parentId;
    case 6: return startTimestamp;
    case 7: return serviceName;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: flightCode = value$ != null ? value$.toString() : null; break;
    case 1: fromCoordinates = (avro.schemas.v1.Coordinates)value$; break;
    case 2: toCoordinates = (avro.schemas.v1.Coordinates)value$; break;
    case 3: uuid = value$ != null ? value$.toString() : null; break;
    case 4: traceId = value$ != null ? value$.toString() : null; break;
    case 5: parentId = (java.lang.Long)value$; break;
    case 6: startTimestamp = (java.lang.Long)value$; break;
    case 7: serviceName = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'flightCode' field.
   * @return The value of the 'flightCode' field.
   */
  public java.lang.String getFlightCode() {
    return flightCode;
  }


  /**
   * Sets the value of the 'flightCode' field.
   * @param value the value to set.
   */
  public void setFlightCode(java.lang.String value) {
    this.flightCode = value;
  }

  /**
   * Gets the value of the 'fromCoordinates' field.
   * @return The value of the 'fromCoordinates' field.
   */
  public avro.schemas.v1.Coordinates getFromCoordinates() {
    return fromCoordinates;
  }


  /**
   * Sets the value of the 'fromCoordinates' field.
   * @param value the value to set.
   */
  public void setFromCoordinates(avro.schemas.v1.Coordinates value) {
    this.fromCoordinates = value;
  }

  /**
   * Gets the value of the 'toCoordinates' field.
   * @return The value of the 'toCoordinates' field.
   */
  public avro.schemas.v1.Coordinates getToCoordinates() {
    return toCoordinates;
  }


  /**
   * Sets the value of the 'toCoordinates' field.
   * @param value the value to set.
   */
  public void setToCoordinates(avro.schemas.v1.Coordinates value) {
    this.toCoordinates = value;
  }

  /**
   * Gets the value of the 'uuid' field.
   * @return The value of the 'uuid' field.
   */
  public java.lang.String getUuid() {
    return uuid;
  }


  /**
   * Sets the value of the 'uuid' field.
   * @param value the value to set.
   */
  public void setUuid(java.lang.String value) {
    this.uuid = value;
  }

  /**
   * Gets the value of the 'traceId' field.
   * @return The value of the 'traceId' field.
   */
  public java.lang.String getTraceId() {
    return traceId;
  }


  /**
   * Sets the value of the 'traceId' field.
   * @param value the value to set.
   */
  public void setTraceId(java.lang.String value) {
    this.traceId = value;
  }

  /**
   * Gets the value of the 'parentId' field.
   * @return The value of the 'parentId' field.
   */
  public long getParentId() {
    return parentId;
  }


  /**
   * Sets the value of the 'parentId' field.
   * @param value the value to set.
   */
  public void setParentId(long value) {
    this.parentId = value;
  }

  /**
   * Gets the value of the 'startTimestamp' field.
   * @return The value of the 'startTimestamp' field.
   */
  public long getStartTimestamp() {
    return startTimestamp;
  }


  /**
   * Sets the value of the 'startTimestamp' field.
   * @param value the value to set.
   */
  public void setStartTimestamp(long value) {
    this.startTimestamp = value;
  }

  /**
   * Gets the value of the 'serviceName' field.
   * @return The value of the 'serviceName' field.
   */
  public java.lang.String getServiceName() {
    return serviceName;
  }


  /**
   * Sets the value of the 'serviceName' field.
   * @param value the value to set.
   */
  public void setServiceName(java.lang.String value) {
    this.serviceName = value;
  }

  /**
   * Creates a new FlightRequest RecordBuilder.
   * @return A new FlightRequest RecordBuilder
   */
  public static avro.schemas.v1.FlightRequest.Builder newBuilder() {
    return new avro.schemas.v1.FlightRequest.Builder();
  }

  /**
   * Creates a new FlightRequest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FlightRequest RecordBuilder
   */
  public static avro.schemas.v1.FlightRequest.Builder newBuilder(avro.schemas.v1.FlightRequest.Builder other) {
    if (other == null) {
      return new avro.schemas.v1.FlightRequest.Builder();
    } else {
      return new avro.schemas.v1.FlightRequest.Builder(other);
    }
  }

  /**
   * Creates a new FlightRequest RecordBuilder by copying an existing FlightRequest instance.
   * @param other The existing instance to copy.
   * @return A new FlightRequest RecordBuilder
   */
  public static avro.schemas.v1.FlightRequest.Builder newBuilder(avro.schemas.v1.FlightRequest other) {
    if (other == null) {
      return new avro.schemas.v1.FlightRequest.Builder();
    } else {
      return new avro.schemas.v1.FlightRequest.Builder(other);
    }
  }

  /**
   * RecordBuilder for FlightRequest instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FlightRequest>
    implements org.apache.avro.data.RecordBuilder<FlightRequest> {

    private java.lang.String flightCode;
    private avro.schemas.v1.Coordinates fromCoordinates;
    private avro.schemas.v1.Coordinates.Builder fromCoordinatesBuilder;
    private avro.schemas.v1.Coordinates toCoordinates;
    private avro.schemas.v1.Coordinates.Builder toCoordinatesBuilder;
    private java.lang.String uuid;
    private java.lang.String traceId;
    private long parentId;
    private long startTimestamp;
    private java.lang.String serviceName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.schemas.v1.FlightRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.flightCode)) {
        this.flightCode = data().deepCopy(fields()[0].schema(), other.flightCode);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.fromCoordinates)) {
        this.fromCoordinates = data().deepCopy(fields()[1].schema(), other.fromCoordinates);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasFromCoordinatesBuilder()) {
        this.fromCoordinatesBuilder = avro.schemas.v1.Coordinates.newBuilder(other.getFromCoordinatesBuilder());
      }
      if (isValidValue(fields()[2], other.toCoordinates)) {
        this.toCoordinates = data().deepCopy(fields()[2].schema(), other.toCoordinates);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasToCoordinatesBuilder()) {
        this.toCoordinatesBuilder = avro.schemas.v1.Coordinates.newBuilder(other.getToCoordinatesBuilder());
      }
      if (isValidValue(fields()[3], other.uuid)) {
        this.uuid = data().deepCopy(fields()[3].schema(), other.uuid);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.traceId)) {
        this.traceId = data().deepCopy(fields()[4].schema(), other.traceId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.parentId)) {
        this.parentId = data().deepCopy(fields()[5].schema(), other.parentId);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.startTimestamp)) {
        this.startTimestamp = data().deepCopy(fields()[6].schema(), other.startTimestamp);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.serviceName)) {
        this.serviceName = data().deepCopy(fields()[7].schema(), other.serviceName);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing FlightRequest instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.schemas.v1.FlightRequest other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.flightCode)) {
        this.flightCode = data().deepCopy(fields()[0].schema(), other.flightCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.fromCoordinates)) {
        this.fromCoordinates = data().deepCopy(fields()[1].schema(), other.fromCoordinates);
        fieldSetFlags()[1] = true;
      }
      this.fromCoordinatesBuilder = null;
      if (isValidValue(fields()[2], other.toCoordinates)) {
        this.toCoordinates = data().deepCopy(fields()[2].schema(), other.toCoordinates);
        fieldSetFlags()[2] = true;
      }
      this.toCoordinatesBuilder = null;
      if (isValidValue(fields()[3], other.uuid)) {
        this.uuid = data().deepCopy(fields()[3].schema(), other.uuid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.traceId)) {
        this.traceId = data().deepCopy(fields()[4].schema(), other.traceId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.parentId)) {
        this.parentId = data().deepCopy(fields()[5].schema(), other.parentId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.startTimestamp)) {
        this.startTimestamp = data().deepCopy(fields()[6].schema(), other.startTimestamp);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.serviceName)) {
        this.serviceName = data().deepCopy(fields()[7].schema(), other.serviceName);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'flightCode' field.
      * @return The value.
      */
    public java.lang.String getFlightCode() {
      return flightCode;
    }


    /**
      * Sets the value of the 'flightCode' field.
      * @param value The value of 'flightCode'.
      * @return This builder.
      */
    public avro.schemas.v1.FlightRequest.Builder setFlightCode(java.lang.String value) {
      validate(fields()[0], value);
      this.flightCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'flightCode' field has been set.
      * @return True if the 'flightCode' field has been set, false otherwise.
      */
    public boolean hasFlightCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'flightCode' field.
      * @return This builder.
      */
    public avro.schemas.v1.FlightRequest.Builder clearFlightCode() {
      flightCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'fromCoordinates' field.
      * @return The value.
      */
    public avro.schemas.v1.Coordinates getFromCoordinates() {
      return fromCoordinates;
    }


    /**
      * Sets the value of the 'fromCoordinates' field.
      * @param value The value of 'fromCoordinates'.
      * @return This builder.
      */
    public avro.schemas.v1.FlightRequest.Builder setFromCoordinates(avro.schemas.v1.Coordinates value) {
      validate(fields()[1], value);
      this.fromCoordinatesBuilder = null;
      this.fromCoordinates = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'fromCoordinates' field has been set.
      * @return True if the 'fromCoordinates' field has been set, false otherwise.
      */
    public boolean hasFromCoordinates() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'fromCoordinates' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public avro.schemas.v1.Coordinates.Builder getFromCoordinatesBuilder() {
      if (fromCoordinatesBuilder == null) {
        if (hasFromCoordinates()) {
          setFromCoordinatesBuilder(avro.schemas.v1.Coordinates.newBuilder(fromCoordinates));
        } else {
          setFromCoordinatesBuilder(avro.schemas.v1.Coordinates.newBuilder());
        }
      }
      return fromCoordinatesBuilder;
    }

    /**
     * Sets the Builder instance for the 'fromCoordinates' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public avro.schemas.v1.FlightRequest.Builder setFromCoordinatesBuilder(avro.schemas.v1.Coordinates.Builder value) {
      clearFromCoordinates();
      fromCoordinatesBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'fromCoordinates' field has an active Builder instance
     * @return True if the 'fromCoordinates' field has an active Builder instance
     */
    public boolean hasFromCoordinatesBuilder() {
      return fromCoordinatesBuilder != null;
    }

    /**
      * Clears the value of the 'fromCoordinates' field.
      * @return This builder.
      */
    public avro.schemas.v1.FlightRequest.Builder clearFromCoordinates() {
      fromCoordinates = null;
      fromCoordinatesBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'toCoordinates' field.
      * @return The value.
      */
    public avro.schemas.v1.Coordinates getToCoordinates() {
      return toCoordinates;
    }


    /**
      * Sets the value of the 'toCoordinates' field.
      * @param value The value of 'toCoordinates'.
      * @return This builder.
      */
    public avro.schemas.v1.FlightRequest.Builder setToCoordinates(avro.schemas.v1.Coordinates value) {
      validate(fields()[2], value);
      this.toCoordinatesBuilder = null;
      this.toCoordinates = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'toCoordinates' field has been set.
      * @return True if the 'toCoordinates' field has been set, false otherwise.
      */
    public boolean hasToCoordinates() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'toCoordinates' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public avro.schemas.v1.Coordinates.Builder getToCoordinatesBuilder() {
      if (toCoordinatesBuilder == null) {
        if (hasToCoordinates()) {
          setToCoordinatesBuilder(avro.schemas.v1.Coordinates.newBuilder(toCoordinates));
        } else {
          setToCoordinatesBuilder(avro.schemas.v1.Coordinates.newBuilder());
        }
      }
      return toCoordinatesBuilder;
    }

    /**
     * Sets the Builder instance for the 'toCoordinates' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public avro.schemas.v1.FlightRequest.Builder setToCoordinatesBuilder(avro.schemas.v1.Coordinates.Builder value) {
      clearToCoordinates();
      toCoordinatesBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'toCoordinates' field has an active Builder instance
     * @return True if the 'toCoordinates' field has an active Builder instance
     */
    public boolean hasToCoordinatesBuilder() {
      return toCoordinatesBuilder != null;
    }

    /**
      * Clears the value of the 'toCoordinates' field.
      * @return This builder.
      */
    public avro.schemas.v1.FlightRequest.Builder clearToCoordinates() {
      toCoordinates = null;
      toCoordinatesBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'uuid' field.
      * @return The value.
      */
    public java.lang.String getUuid() {
      return uuid;
    }


    /**
      * Sets the value of the 'uuid' field.
      * @param value The value of 'uuid'.
      * @return This builder.
      */
    public avro.schemas.v1.FlightRequest.Builder setUuid(java.lang.String value) {
      validate(fields()[3], value);
      this.uuid = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'uuid' field has been set.
      * @return True if the 'uuid' field has been set, false otherwise.
      */
    public boolean hasUuid() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'uuid' field.
      * @return This builder.
      */
    public avro.schemas.v1.FlightRequest.Builder clearUuid() {
      uuid = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'traceId' field.
      * @return The value.
      */
    public java.lang.String getTraceId() {
      return traceId;
    }


    /**
      * Sets the value of the 'traceId' field.
      * @param value The value of 'traceId'.
      * @return This builder.
      */
    public avro.schemas.v1.FlightRequest.Builder setTraceId(java.lang.String value) {
      validate(fields()[4], value);
      this.traceId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'traceId' field has been set.
      * @return True if the 'traceId' field has been set, false otherwise.
      */
    public boolean hasTraceId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'traceId' field.
      * @return This builder.
      */
    public avro.schemas.v1.FlightRequest.Builder clearTraceId() {
      traceId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'parentId' field.
      * @return The value.
      */
    public long getParentId() {
      return parentId;
    }


    /**
      * Sets the value of the 'parentId' field.
      * @param value The value of 'parentId'.
      * @return This builder.
      */
    public avro.schemas.v1.FlightRequest.Builder setParentId(long value) {
      validate(fields()[5], value);
      this.parentId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'parentId' field has been set.
      * @return True if the 'parentId' field has been set, false otherwise.
      */
    public boolean hasParentId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'parentId' field.
      * @return This builder.
      */
    public avro.schemas.v1.FlightRequest.Builder clearParentId() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'startTimestamp' field.
      * @return The value.
      */
    public long getStartTimestamp() {
      return startTimestamp;
    }


    /**
      * Sets the value of the 'startTimestamp' field.
      * @param value The value of 'startTimestamp'.
      * @return This builder.
      */
    public avro.schemas.v1.FlightRequest.Builder setStartTimestamp(long value) {
      validate(fields()[6], value);
      this.startTimestamp = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'startTimestamp' field has been set.
      * @return True if the 'startTimestamp' field has been set, false otherwise.
      */
    public boolean hasStartTimestamp() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'startTimestamp' field.
      * @return This builder.
      */
    public avro.schemas.v1.FlightRequest.Builder clearStartTimestamp() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'serviceName' field.
      * @return The value.
      */
    public java.lang.String getServiceName() {
      return serviceName;
    }


    /**
      * Sets the value of the 'serviceName' field.
      * @param value The value of 'serviceName'.
      * @return This builder.
      */
    public avro.schemas.v1.FlightRequest.Builder setServiceName(java.lang.String value) {
      validate(fields()[7], value);
      this.serviceName = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'serviceName' field has been set.
      * @return True if the 'serviceName' field has been set, false otherwise.
      */
    public boolean hasServiceName() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'serviceName' field.
      * @return This builder.
      */
    public avro.schemas.v1.FlightRequest.Builder clearServiceName() {
      serviceName = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FlightRequest build() {
      try {
        FlightRequest record = new FlightRequest();
        record.flightCode = fieldSetFlags()[0] ? this.flightCode : (java.lang.String) defaultValue(fields()[0]);
        if (fromCoordinatesBuilder != null) {
          try {
            record.fromCoordinates = this.fromCoordinatesBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("fromCoordinates"));
            throw e;
          }
        } else {
          record.fromCoordinates = fieldSetFlags()[1] ? this.fromCoordinates : (avro.schemas.v1.Coordinates) defaultValue(fields()[1]);
        }
        if (toCoordinatesBuilder != null) {
          try {
            record.toCoordinates = this.toCoordinatesBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("toCoordinates"));
            throw e;
          }
        } else {
          record.toCoordinates = fieldSetFlags()[2] ? this.toCoordinates : (avro.schemas.v1.Coordinates) defaultValue(fields()[2]);
        }
        record.uuid = fieldSetFlags()[3] ? this.uuid : (java.lang.String) defaultValue(fields()[3]);
        record.traceId = fieldSetFlags()[4] ? this.traceId : (java.lang.String) defaultValue(fields()[4]);
        record.parentId = fieldSetFlags()[5] ? this.parentId : (java.lang.Long) defaultValue(fields()[5]);
        record.startTimestamp = fieldSetFlags()[6] ? this.startTimestamp : (java.lang.Long) defaultValue(fields()[6]);
        record.serviceName = fieldSetFlags()[7] ? this.serviceName : (java.lang.String) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FlightRequest>
    WRITER$ = (org.apache.avro.io.DatumWriter<FlightRequest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FlightRequest>
    READER$ = (org.apache.avro.io.DatumReader<FlightRequest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.flightCode);

    if (this.fromCoordinates == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      this.fromCoordinates.customEncode(out);
    }

    if (this.toCoordinates == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      this.toCoordinates.customEncode(out);
    }

    out.writeString(this.uuid);

    out.writeString(this.traceId);

    out.writeLong(this.parentId);

    out.writeLong(this.startTimestamp);

    out.writeString(this.serviceName);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.flightCode = in.readString();

      if (in.readIndex() != 0) {
        in.readNull();
        this.fromCoordinates = null;
      } else {
        if (this.fromCoordinates == null) {
          this.fromCoordinates = new avro.schemas.v1.Coordinates();
        }
        this.fromCoordinates.customDecode(in);
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.toCoordinates = null;
      } else {
        if (this.toCoordinates == null) {
          this.toCoordinates = new avro.schemas.v1.Coordinates();
        }
        this.toCoordinates.customDecode(in);
      }

      this.uuid = in.readString();

      this.traceId = in.readString();

      this.parentId = in.readLong();

      this.startTimestamp = in.readLong();

      this.serviceName = in.readString();

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.flightCode = in.readString();
          break;

        case 1:
          if (in.readIndex() != 0) {
            in.readNull();
            this.fromCoordinates = null;
          } else {
            if (this.fromCoordinates == null) {
              this.fromCoordinates = new avro.schemas.v1.Coordinates();
            }
            this.fromCoordinates.customDecode(in);
          }
          break;

        case 2:
          if (in.readIndex() != 0) {
            in.readNull();
            this.toCoordinates = null;
          } else {
            if (this.toCoordinates == null) {
              this.toCoordinates = new avro.schemas.v1.Coordinates();
            }
            this.toCoordinates.customDecode(in);
          }
          break;

        case 3:
          this.uuid = in.readString();
          break;

        case 4:
          this.traceId = in.readString();
          break;

        case 5:
          this.parentId = in.readLong();
          break;

        case 6:
          this.startTimestamp = in.readLong();
          break;

        case 7:
          this.serviceName = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










